Automate API documentation generation

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -75,6 +75,58 @@ jobs:
 
             cd dist
             npm publish --tag ${NPM_TAG}
+                        
+  deploy_docs:
+    <<: *defaults
+
+    steps:
+      - add_ssh_keys:
+          fingerprints:
+            - "88:40:77:16:49:23:99:69:df:a3:ad:ac:21:ec:b3:8e"
+
+      - attach_workspace:
+          at: *workspace_root
+
+      - run:
+          name: Auth with github
+          command: |
+            mkdir -p ~/.ssh/
+            ssh-keyscan -Ht rsa github.com >> ~/.ssh/known_hosts
+
+      - run:
+          name: Publish gh-pages
+          command: |
+            # Fail script when any non-zero command
+            set -e
+
+            # Config GIT
+            git config --global user.email "$GH_EMAIL"
+            git config --global user.name "$GH_NAME"
+
+            # Clone GitHub Pages branch
+            git clone --single-branch --branch gh-pages $CIRCLE_REPOSITORY_URL gh-pages
+
+            # Clean GitHub Pages
+            echo -e "\nClean gh-pages directory"
+            cd gh-pages
+            git rm -rf .
+
+            # Copy docs to GitHub Pages
+            echo -e "\nCopy docs into gh-pages directory"
+            cd ..
+            cp -av docs/* gh-pages
+            # Copy Circle CI config
+            mkdir -p gh-pages/.circleci
+            cp -av .circleci/config.yml gh-pages/.circleci/config.yml
+            # Add .nojekyll file
+            touch .nojekyll
+
+            # Publish new GitHub Pages
+            echo -e "\nDeploy gh-pages branch"
+            cd gh-pages
+            git add -A
+            git commit -m "Circle CI deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty
+            git push origin gh-pages
 workflows:
   version: 2
   build_and_deploy:
@@ -103,3 +155,11 @@ workflows:
               ignore: /.*/
             tags:
               only: /^v\d+\.\d+\.\d+(-.+)?/
+      - deploy_docs:
+          requires:
+            - deploy_npm
+          filters:
+            branches:
+              ignore: /.*/
+            tags:
+              only: /^v\d+\.\d+\.\d+$/
